-- AlterTable
ALTER TABLE "tour_schedules" ADD COLUMN     "kmPerDay" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ratePerDay" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "seats" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "vehicleNo" TEXT;
